name: Run Python Script Every 10 Hours

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:        # Allows you to run it manually for testing

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install Requirements
        run: |
          pip install requests pycryptodomex

      - name: Download and Run Script
        env:
          REAL_URL: ${{ secrets.DASHTV }}
        run: |
          curl -L $REAL_URL -o script.py
          python script.py > cookie.txt

      - name: Commit and Push output
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add cookie.txt
          git commit -m "Update output dastv.m3u" || echo "No changes to commit"
          git push
